### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by yutv** [ANYbotics/gnome-shell-ping-monitor-applet#9]
Sometimes after screen lock and login, sometimes after orientation change on convertible laptop (HP x360), sometimes after disabling/enabling the ping-monitor extension the duplicates show up in the top gnome bar. Please see the screencast attached.

![ping-monitor](https://user-images.githubusercontent.com/1616522/67185300-2cbf2080-f3ee-11e9-82b4-6dc1d9edb4b5.gif)

-----
Ubuntu 18.04.3 LTS (Bionic Beaver)
GNOME Shell 3.28.4

**Comment by samuelba** [comment]
I'm aware of this issue. There was a version which didn't have this issue. But it didn't get approved on extensions.gnome.org because the clean up throw some exceptions when you looked at the gnome console. I "solved" the exceptions but that resulted in a not very robust clean up.

If you have some expertise with gnome and Javascript you are welcome to look into this issue.

**Comment by Joshfindit** [comment]
@samuelba Can you point us towards that version so that those who don't mind can install it manually?

**Comment by samuelba** [comment]
@Joshfindit That should be the second last commit: https://github.com/ANYbotics/gnome-shell-ping-monitor-applet/tree/c818a56eb290f57a5f4394f44f1e761217491912

**Comment by samuelba** [comment]
This should be fixed here https://github.com/ANYbotics/gnome-shell-ping-monitor-applet/commit/5c8c2720c0ae97c09c278b73cf024a08aca6f68b
